name: Pipeline
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            ALGORITHM: ${{ secrets.ALGORITHM }}
            ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

        steps:
            - name: Install python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install poetry
              run: pipx install poetry
            
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Install dependencies
              run: poetry install
            
            - name: Excecute tests
              run: poetry run task test
